---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: ashkt/calculator:latest
        source: pull
    - name: Running container
      shell: /usr/local/bin/docker run -it -d --name Calculator ashkt/calculator
